/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thaiddd_javaguiex_core_Dump */

#ifndef _Included_com_thaiddd_javaguiex_core_Dump
#define _Included_com_thaiddd_javaguiex_core_Dump
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    devList
 * Signature: ([Lcom/thaiddd/javaguiex/core/NICDevice;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thaiddd_javaguiex_core_Dump_devList
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    openDev
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thaiddd_javaguiex_core_Dump_openDev
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    setFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thaiddd_javaguiex_core_Dump_setFilter
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    loop
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_thaiddd_javaguiex_core_Dump_loop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    readFromUserBuff
 * Signature: (Lcom/thaiddd/javaguiex/core/TcpDataBlock;)I
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_readFromUserBuff
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
