/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thaiddd_javaguiex_NativeC */

#ifndef _Included_com_thaiddd_javaguiex_NativeC
#define _Included_com_thaiddd_javaguiex_NativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thaiddd_javaguiex_NativeC
 * Method:    nativeDecStr
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_thaiddd_javaguiex_NativeC_nativeDecStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_thaiddd_javaguiex_NativeC
 * Method:    nativeDecBin
 * Signature: ([B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_thaiddd_javaguiex_NativeC_nativeDecBin
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
